### PR TITLE
Configure debugging in VSCode.

### PR DESCRIPTION
**Pull request by jjrv**

### CODE REVIEW

**Review by ISNIT0 — CHANGES_REQUESTED** [review]
The `launch.json` file is in the `src/` directory, which means that VSCode doesn't detect it, making the config mostly useless.

**Comment by jjrv** [comment]
I always open the `src` folder in VSCode so everything works and the tree in its left side panel is less cluttered. Maybe that's an unexpected / unwanted assumption for potential contributors. I'll try out the alternative then...

**Comment by ISNIT0** [comment]
Hmm, I *think* (based on experience in private projects) that the industry standard is to have `.vscode` in the root of the project, rather than the `src`

**Comment by jjrv** [comment]
How about this? Open the root folder and VSCode prompts to open the workspace. Then hit ctrl+shift+b (or tell it to run the example) and it builds and starts watching for changes. Debugging works.

Tree on the left shows only the `src` and `example` dirs (the `test` would be added in the next commit).

**Comment by jjrv** [comment]
This way the package looks clean without a config directory at the top. `test` and `.travis.yml` still need to be added but there's nothing "unnecessary" visible when entering the GitHub repo, except `index.html` and a VSCode config file at the end.

**Review by ISNIT0 — APPROVED** [review]

**Pull request merged**
